#!/bin/sh
#
# Start xenbr0 after eth0 is up. Used instead of `auto xenbr0` in
# the interface config to work around issues with cloud-init
# and non-physical auto interfaces.

[ "$IFACE" != "eth0" ] || exit 0

ifup xenbr0
